#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.openai_api_key = "01234567890123456789"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.2ba5ff6e94a0e401122e4eb894fdae69df4f0882.name = "Upgrade from 0.9.64~ynh1"
