#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="${app}_admin_frontend" --action="stop"
ynh_systemctl --service="${app}_cloud" --action="stop"
ynh_systemctl --service="${app}_worker" --action="stop"
ynh_systemctl --service="${app}_ai" --action="stop"
ynh_systemctl --service="${app}_gotrue" --action="stop"
ynh_systemctl --service="${app}_minio" --action="stop"
ynh_systemctl --service="${app}_web" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

domain=$new_domain

ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="appflowy_minio.env" --destination="$install_dir/appflowy_minio/.env"
chmod 400 "$install_dir/appflowy_minio/.env"
chown "$app:$app" "$install_dir/appflowy_minio/.env"

local_hostname=$(hostname)
ynh_config_add --template="appflowy_gotrue.env" --destination="$install_dir/appflowy_gotrue/.env"
chmod 400 "$install_dir/appflowy_gotrue/.env"
chown "$app:$app" "$install_dir/appflowy_gotrue/.env"

ynh_config_add --template="appflowy_ai.env" --destination="$install_dir/appflowy_ai/.env"
chmod 400 "$install_dir/appflowy_ai/.env"
chown "$app:$app" "$install_dir/appflowy_ai/.env"

ynh_config_add --template="appflowy_worker.env" --destination="$install_dir/appflowy_worker/.env"
chmod 400 "$install_dir/appflowy_worker/.env"
chown "$app:$app" "$install_dir/appflowy_worker/.env"

ynh_config_add --template="appflowy_cloud.env" --destination="$install_dir/appflowy_cloud/.env"
chmod 400 "$install_dir/appflowy_cloud/.env"
chown "$app:$app" "$install_dir/appflowy_cloud/.env"

ynh_config_add --template="appflowy_admin_frontend.env" --destination="$install_dir/appflowy_admin_frontend/.env"
chmod 400 "$install_dir/appflowy_admin_frontend/.env"
chown "$app:$app" "$install_dir/appflowy_admin_frontend/.env"

ynh_config_add --template="appflowy_web.env" --destination="$install_dir/appflowy_web/.env"
chmod 400 "$install_dir/appflowy_web/.env"
chown "$app:$app" "$install_dir/appflowy_web/.env"

# We need to authorize the new domain in the web app vite config -> replace the allowedHosts entry
pushd "$install_dir/appflowy_web"
    # We don't know how to get the old domain value, so this doesn't work
    #ynh_replace --match="allowedHosts: ['$old_domain']" --replace="allowedHosts: ['$domain']" --file="vite.config.ts"
    # So we just add the new domain to the allowedHosts array
    ynh_replace --match="allowedHosts: \[" --replace="allowedHosts: ['$domain'," --file="vite.config.ts"
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="${app}_minio" --action="start" --log_path="/var/log/$app/${app}_minio.log" --wait_until="WebUI:"
ynh_systemctl --service="${app}_gotrue" --action="start" --log_path="/var/log/$app/${app}_gotrue.log" --wait_until="GoTrue API started"
ynh_systemctl --service="${app}_ai" --action="start" --log_path="/var/log/$app/${app}_ai.log" --wait_until="Uvicorn running"
ynh_systemctl --service="${app}_worker" --action="start" --log_path="/var/log/$app/${app}_worker.log" --wait_until="Starting importer worker"
ynh_systemctl --service="${app}_cloud" --action="start" --log_path="/var/log/$app/${app}_cloud.log" --wait_until="Server started"
ynh_systemctl --service="${app}_admin_frontend" --action="start" --log_path="/var/log/$app/${app}_admin_frontend.log" --wait_until="listening on"
ynh_systemctl --service="${app}_web" --action="start" --log_path="/var/log/$app/${app}_web.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
